package com.example.pomochan

object Constants {
    const val NOTIFICATION_CHANNEL_ID = "timer_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Timer"
    const val NOTIFICATION_ID = 1

    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"

    const val ACTION_SHOW_MAIN_FRAGMENT = "ACTION_SHOW_MAIN_FRAGMENT"
    const val ACTION_SHOW_SHORTBREAK_FRAGMENT = "ACTION_SHOW_SHORTBREAK_FRAGMENT"
    const val ACTION_SHOW_LONGBREAK_FRAGMENT = "ACTION_SHOW_LONGBREAK_FRAGMENT"

    const val EXTRA_MAIN_TIMER_ACTIVE = "ACTION_MAIN_TIMER_ACTIVE"
    const val ACTION_SHORTBREAK_TIMER_ACTIVE = "ACTION_SHORTBREAK_TIMER_ACTIVE"
    const val ACTION_LONGBREAK_TIMER_ACTIVE = "ACTION_LONGBREAK_TIMER_ACTIVE"

    const val EXTRA_TIMER = "com.example.pomochan.TIMER"
    const val EXTRA_SHORTBREAK = "com.example.pomochan.SHORTBREAK"
    const val EXTRA_LONGBREAK = "com.example.pomochan.LONGBREAK"
}